<<<<<<< HEAD
theme: jekyll-theme-minima
title: STAR TEKNOLOJİ
description: StarTeknoloji Hoşgeldiniz !!!
  
=======
theme: jekyll-theme-minima 
title: STAR ComputerSpace
description: StarComputerSpace Hoşgeldiniz [Google Haritalar]
twitter: guler_ercetin
email: user@starcomputer.space
>>>>>>> 4a4f5382985f711c3736f4fac8835ce05b2fb1ff
