theme: jekyll-theme-architect 
title: (* StAR tEKNOLOJİ
description: Hoşgeldiniz ... Google Arama Motoru, Github ve Google Haritalarda Bulabilirsiniz.Bize ayırdığınız Vakit İçin Teşekkürler.
project: Starsuff
indescription: Star Technology Area 
app: StarTeknoloji AreCods
yazar:  Erçetin Güler
izleme:   UA-240549066-1
