theme: jekyll-theme-architect 
title: (* STAR Teknoloji 
description: Hoşgeldiniz *Star Teknoloji Hİzmetinizde. Google Haritalar ve Github Sayfalarında Bulabilirsiniz. Bİze Ayırdığınız Vakit için Teşekkür ederiz.
yazar:  Erçetin Güler
